#!/bin/sh

Clock() {
	echo -e "\Uf0954 $(date +"%d.%m.%Y %H.%M.%S")"
}

Brightness() {
	echo -e "\Uf00de $(brightnessctl i | grep -oP "\d{3}%")"
}

Volume() {
	local label="$2"
	local volume
	local isMute

	read volume isMute <<< $(amixer sget "$1" | tail -n 1 | awk -F'[][]' '{print $2,($6 == "off")}')

	if [ "$isMute" = "1" ]; then
		label="$3"
	fi

	echo -e "$label $volume"
}

declare -A keymaps

keymaps["0000000"]="us"
keymaps["0000100"]="ua"

Keyboard() {
	local led="$(xset -q | grep "LED" | grep -oP "\d{7}")"
	local keymap="${keymaps["$led"]}"
	local capslock="$(xset -q | grep -oP "Caps Lock:\s*(on|off)" | awk '{print ($3 == "on" ? "C" : "c")}')"
	local numlock="$(xset -q | grep -oP "Num Lock:\s*(on|off)" | awk '{print ($3 == "on" ? "N" : "n")}')"

	echo -e "$capslock$numlock - \Uf030c $keymap"
}

while true; do
	xsetroot -name "$(Keyboard) | $(Volume "Master" "\Uf027" "\Uf075f") $(Volume "Speaker" "\Uf036c" "\Uf036d") | $(Brightness) | $(Clock)"

	sleep 1 && wait
done

